from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CostumeThemeAssets: 


	# Image Rule Assets
	# description 
	I_THEME1_LOGIN_SCROOLL_CLOSE_1 = RuleImage(roi_front=(1195,650,48,52), roi_back=(1193,649,51,54), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeTheme/theme1/theme1_login_scrooll_close.png")
	# description 
	I_THEME1_LOGIN_SCROOLL_OPEN_1 = RuleImage(roi_front=(1214,607,27,64), roi_back=(1213,606,30,66), threshold=0.8, method="Template matching", file="./tasks/Component/CostumeTheme/theme1/theme1_login_scrooll_open.png")

